language: node_js
node_js:
- node
before_script:
- npm install -g bower
- npm install -g polymer-cli
- bower i
script: polymer build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/es6-bundled
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master